apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: gcr.io/quantum-star-435523-g9/backend-suscriber:latest
          ports:
            - containerPort: 5000
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/gcp-credentials/service-account.json"
          volumeMounts:
            - name: gcp-service-account-volume
              mountPath: /app/gcp-credentials
              readOnly: true
      volumes:
        - name: gcp-service-account-volume
          secret:
            secretName: gcp-service-account-secret
            items:
              - key: service-account.json
                path: service-account.json
      imagePullSecrets:
        - name: gcr-json-key
