apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 3 # Number of desired replicas
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: gcr.io/quantum-star-435523-g9/flask-app-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/quantum-star-435523-g9-1d6e0f9df362.json"
          volumeMounts:
            - name: gcp-service-account-volume
              mountPath: /app/quantum-star-435523-g9-1d6e0f9df362.json
              subPath: quantum-star-435523-g9-1d6e0f9df362.json
      volumes:
        - name: gcp-service-account-volume
          secret:
            secretName: gcp-service-account-secret
      imagePullSecrets:
        - name: gcr-json-key
